### ISSUE TITLE
Greet

### ISSUE THREAD

**Issue by HyKung** [GamesTrap/TRAP#98]
Hello! Have you made any games using this engine? Expect to see more visualizations!

**Comment by GamesTrap** [comment]
Hi, the engine is still in its early days, I haven't released a game with it **yet** and I'm unaware if somebody else has.
I'm also still working on core features like the editor, audio, multi-threading and so on.

**Comment by HyKung** [comment]
> Hi, the engine is still in its early days, I haven't released a game with it **yet** and I'm unaware if somebody else has. I'm also still working on core features like the editor, audio, multi-threading and so on.
OK,Just looking forward to your game and technical documentation!

**Comment by HyKung** [comment]
OK,Just looking forward to your game and technical documentation!

**Comment by GamesTrap** [comment]
Do you have any more questions or can this issue be closed?
